# Site
title:              DevRel Meetup in Tokyo
bio:                'エバンジェリスト、アドボケイトそしてすべての開発者向けマーケティングを行う方達のコミュニティ'
description:        "DevRel Meetup in Tokyoはエバンジェリスト、アドボケイト、<br />そしてすべての開発者向けマーケティングを行う方達のコミュニティです"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/new-org-logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ja_JP
url:                https://devrel.tokyo

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   devrel-meetup-in-tokyo

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics: UA-48936410-11
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: info@devrel.tokyo
twitter:            devrelTokyo
facebook:           devreltokyo
#github-url:         https://github.com/DevRelMeetupTokyo/
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
youtube-channel:   https://www.youtube.com/channel/UC0ZgE2vnoQfTe0O3dufsb1w
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
slack:              https://bit.ly/devreljp-invite
connpass:           https://devrel.connpass.com
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]


podcast_url: /podcast.xml

podcast:
  title: DevRel/Radio
  description: DevRel/Radioは耳で楽しめるDevRelコンテンツです。毎週水曜日17時からリアルタイム配信しています。
  url: /podcast.xml
  author: DevRel/Radio
  email: info@devrel.tokyo
  logo: https://devrel.tokyo/assets/img/new-org-logo.png
  language: ja
  category: Business
  subcategory: [Marketing]
  type: episodic
  explicit: false
  complete: no
  block: yes
